const path=require('path'),fs=require('fs'),assert=require('assert/strict'),{chromium,devices}=require('playwright');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--enable-webgl','--enable-unsafe-swiftshader','--use-gl=angle','--use-angle=swiftshader']});let source=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');source=source.replace('  requestAnimationFrame(frame);\n})();',fs.readFileSync(path.join(__dirname,'browser-observability.js'),'utf8')+'\n  requestAnimationFrame(frame);\n})();');const report=[];const appUrl=process.env.SPACE_APP_TEST_URL||'http://127.0.0.1:8770/';
for(const profile of ['PC','iPhone']){const page=await browser.newPage(profile==='PC'?{viewport:{width:1000,height:760}}:{...devices['iPhone 13'],viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('404'))errors.push(m.text())});await page.addInitScript(()=>{localStorage.setItem('ssm_lite','1');window.__frames=0;const r=requestAnimationFrame;window.requestAnimationFrame=cb=>r.call(window,t=>{__frames++;cb(t)})});await page.route(appUrl,r=>r.fulfill({contentType:'text/html',body:source}));await page.goto(appUrl,{waitUntil:'commit'});await page.waitForFunction(()=>window.__showsState);
const frame=async()=>{const n=await page.evaluate(()=>__frames);await page.waitForFunction(n=>__frames>=n+2,n)};
const click=async s=>{await page.evaluate(s=>document.querySelector(s).click(),s);await frame()};const state=()=>page.evaluate(()=>__showsState());const seek=async t=>{await page.evaluate(t=>__showsSeek(t),t);await frame();const s=await state();assert(s.finite&&!s.error&&!errors.length,JSON.stringify({s,errors}));return s};
const samples={jupiter:[],saturn:[],enceladus:[]};
await page.selectOption('#welcomeShowSelect','jupiter');await frame();let s=await state();assert.equal(s.show.kind,'jupiter');assert.equal(s.space.length,18);assert.equal(s.all,34);assert.equal(s.scaleMode,2);assert.equal(s.moonScale,1);assert(s.spinReal);
for(const t of [0,6,10,12,14,18,24,30,36,40,44,46,48,50,52,54,56,60,64,68]){s=await seek(t);samples.jupiter.push({t,phase:s.phase,...s.io});if(t===12)assert(s.ioSizeRatio>.025&&s.ioSizeRatio<.028,'Telescope preserves satellite apparent size');if([12,30,50].includes(t))await page.screenshot({path:'/tmp/celestial-'+profile+'-jupiter-'+t+'.png'});}
assert(samples.jupiter.some(x=>x.transit&&x.shadowVisible),'Transit and shadow');await seek(12);const background=await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>{const c=document.querySelector('canvas'),g=c.getContext('webgl'),samples=[];for(let i=0;i<9;i++){const a=new Uint8Array(4);g.readPixels(Math.floor(c.width*(.90+i*.007)),Math.floor(c.height*.12),1,1,g.RGBA,g.UNSIGNED_BYTE,a);samples.push(Math.max(...a.slice(0,3)));}resolve(samples.sort((a,b)=>a-b)[4]);})));assert(background<20,'Telescope background stays dark');await seek(68);assert(samples.jupiter.some(x=>x.illumination<.1),'Moon eclipses');assert(samples.jupiter.some(x=>x.occulted),'Moon is occulted');assert(samples.jupiter.some(x=>x.illumination<.2&&!x.occulted),'Eclipsed moon visible outside planet');
const paused=await state();await frame();assert.equal((await state()).years,paused.years);await click('#gShowPause');s=await state();assert(!s.show.paused&&s.show.t<5);await click('#gShowPause');assert((await state()).show.paused);await click('#gShowReplay');assert((await state()).show.t<5);
await click('#gNext');assert.equal((await state()).show.kind,'saturn');
for(const t of [0,16,20,24,33,34,40,46,51,56]){s=await seek(t);samples.saturn.push({t,opening:s.opening,phase:s.phase});if([0,20,40].includes(t))await page.screenshot({path:'/tmp/celestial-'+profile+'-saturn-'+t+'.png'});}assert(samples.saturn.some(x=>x.opening<-10)&&samples.saturn.some(x=>x.opening>10));assert(Math.abs(samples.saturn.find(x=>x.t===20).opening)<.001);assert.equal(samples.saturn.find(x=>x.t===40).phase,'above');
await click('#gNext');assert.equal((await state()).show.kind,'enceladus');
for(const t of [0,5,10,20,26,31.5,32,37,45,52,58]){s=await seek(t);samples.enceladus.push({t,phase:s.phase});if(t===31.5){const axial=-s.enceladusOffset.reduce((v,x,i)=>v+x*s.pole[i],0),lateral=Math.hypot(...s.enceladusOffset.map((x,i)=>x+axial*s.pole[i]));assert(axial>1&&axial<3&&lateral<.2,'Camera enters the south polar plume');}if([20,32,58].includes(t))await page.screenshot({path:'/tmp/celestial-'+profile+'-enceladus-'+t+'.png'});}assert(!(await page.locator('#gOceanDiagram').getAttribute('hidden')));await page.locator('#gOceanDiagram summary').click();assert(await page.locator('#gOceanDiagram').getAttribute('open')!==null);await page.locator('#gOceanDiagram summary').click();
// Manual camera movement while paused; stereoscopic and full particle rendering.
const before=(await state()).cam.tth;await page.mouse.move(profile==='PC'?900:230,150);await page.mouse.down();await page.mouse.move(profile==='PC'?980:280,175,{steps:3});await page.mouse.up();await frame();assert.notEqual((await state()).cam.tth,before);
for(const mode of ['parallel','cross','anaglyph','normal']){await click('[data-stereo="'+mode+'"]');s=await state();assert(s.finite&&!s.error)}await click('#bLite');await seek(20);await click('#bLite');
// Moving to the next ordinary scene removes every transient show control.
await click('#gNext');s=await state();assert.equal(s.show,null);assert(await page.locator('#gShowControls').getAttribute('hidden')!==null);await click('#gEnd');
// Starting from a different scale and using a normal destination restores it.
await click('#welcomeExplore');await click('[data-sc="1"]');await click('[data-ms="4"]');await page.selectOption('#celestialShowSelect','jupiter',{force:true});await frame();await seek(12);await click('[data-fo="3"]');s=await state();assert.equal(s.show,null);assert(!s.guideOn);assert.equal(s.scaleMode,1);assert.equal(s.moonScale,4);assert(!s.spinReal);
await page.selectOption('#celestialShowSelect','saturn',{force:true});await frame();await page.evaluate(()=>__showsAdvance());await frame();s=await state();assert.equal(s.show.kind,'enceladus');assert(s.gAuto);
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert(!overflow);assert.equal(errors.length,0,JSON.stringify(errors));report.push({profile,samples,errors,overflow});console.log(JSON.stringify({profile,transit:samples.jupiter.filter(x=>x.transit).length,eclipsed:samples.jupiter.filter(x=>x.illumination<.1).length,saturn:samples.saturn,errors}));await page.close();}
await browser.close();fs.writeFileSync('/tmp/celestial-qa-results.json',JSON.stringify(report,null,2));})().catch(e=>{console.error(e);process.exit(1)});
