const path=require('path'),fs=require('fs'),assert=require('assert/strict'),{chromium,devices}=require('playwright');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--enable-unsafe-swiftshader','--use-angle=swiftshader']});let source=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8').replace('  requestAnimationFrame(frame);\n})();',fs.readFileSync(path.join(__dirname,'browser-observability.js'),'utf8')+'\n  requestAnimationFrame(frame);\n})();');const results=[];const appUrl=process.env.SPACE_APP_TEST_URL||"http://127.0.0.1:8770/";
for(const profile of ['PC','iPhone']){const p=await browser.newPage(profile==='PC'?{viewport:{width:1000,height:760}}:{...devices['iPhone 13'],viewport:{width:390,height:844}});const errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&!m.text().includes('404'))errors.push(m.text())});await p.addInitScript(()=>{localStorage.setItem('ssm_lite','1');window.__frames=0;const r=requestAnimationFrame;window.requestAnimationFrame=cb=>r.call(window,t=>{__frames++;cb(t)})});await p.route(appUrl,r=>r.fulfill({contentType:'text/html',body:source}));await p.goto(appUrl);const frame=async()=>{const n=await p.evaluate(()=>__frames);await p.waitForFunction(n=>__frames>=n+2,n)};const click=async s=>{if(profile==='iPhone')await p.locator(s).tap();else await p.locator(s).click();await frame()};const state=()=>p.evaluate(()=>__showsState());const select=async(s,v)=>{await p.selectOption(s,v);await frame()};
await select('#welcomeShowSelect','jupiter');await click('#gShowPause');await p.evaluate(()=>__showsSeek(12));await frame();let s=await state();assert((await p.locator('#dateIn').inputValue()).startsWith('2026-10-06T02:40'));assert((await p.locator('#scaleInfo').textContent()).includes('分角'));const z=s.cam.td;await p.mouse.move(profile==='PC'?650:195,160);await p.mouse.wheel(0,-120);await frame();assert((await state()).cam.td<z);await p.screenshot({path:'/tmp/celestial-final-'+profile+'-jupiter.png'});await click('#gEnd');
await select('#welcomeShowSelect','enceladus');await p.evaluate(()=>__showsSeek(20));await frame();await p.screenshot({path:'/tmp/celestial-final-'+profile+'-enceladus.png'});await click('#gOceanDiagram summary');await p.screenshot({path:'/tmp/celestial-final-'+profile+'-ocean.png'});await click('#gOceanDiagram summary');await click('#panelToggle');await click('#bLightF');assert((await state()).show===null);assert(!(await state()).guideOn);await click('#bSkip');
// Enter from a moon surface: keep the user's scale from before entering that surface.
if(!(await p.locator('#panelToggle').getAttribute('aria-expanded')).includes('true'))await click('#panelToggle');await click('[data-sc="1"]');await select('#moonTravelSelect','5:0');await click('#bSurface');assert.equal((await state()).scaleMode,2);await select('#celestialShowSelect','saturn');await p.evaluate(()=>__showsSeek(20));await frame();await p.screenshot({path:'/tmp/celestial-final-'+profile+'-saturn.png'});await click('#gEnd');assert.equal((await state()).scaleMode,1);
await select('#welcomeShowSelect','jupiter');await click('#gShowPause');await click('#panelToggle');await p.locator('#dateIn').fill('2026-10-07T21:00');await p.locator('#dateIn').press('Enter');await frame();assert.equal((await state()).show,null);assert.equal(await p.locator('#dateIn').inputValue(),'2026-10-07T21:00');assert.equal(errors.length,0,JSON.stringify(errors));assert(!(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth)));results.push({profile,errors,nativeControls:true,dateInput:true,telescopeZoom:true,surfaceScaleRestoration:true});await p.close();}
await browser.close();fs.writeFileSync('/tmp/celestial-ui-results.json',JSON.stringify(results));console.log(JSON.stringify(results));})().catch(e=>{console.error(e);process.exit(1)});
