const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{test}=require('node:test');
const root=path.join(__dirname,'..'),read=file=>JSON.parse(fs.readFileSync(path.join(root,file))),P=require('../assets/constellations/placement.js'),{apply}=require('../scripts/apply-constellation-calibration.cjs');
const index=read('assets/constellations/index.json'),layout=read('assets/constellations/layout.json'),catalog=read('assets/constellations/catalog.json'),guides=read('assets/constellations/semantic-guides.json'),baseline=read('tests/constellation-placement-baseline.json'),pilot=['Ori','Leo','And','Gem','Peg'];
test('legacy projection retained for all 34, anchors and image hashes unchanged',()=>{
 for(const b of baseline){const i=index.items.find(i=>i.code===b.code);assert.deepEqual(i.anchors,b.anchors);assert.equal(i.sha256,b.hash);assert.equal(i.mobileSha256,b.mobileHash);const f=P.frame(i.anchors);[[0,0],[1,0],[.5,.5],[0,1],[1,1]].forEach((uv,n)=>{const actual=P.direction(f,...uv);assert(actual.every((v,k)=>Math.abs(v-b.points[n][k])<1e-12),i.code);});}
 assert.equal(index.items.filter(i=>i.adjustment).length,34);
 const approved=read('tests/constellation-approved-five.json');for(const code of pilot){assert.deepEqual(index.items.find(i=>i.code===code).adjustment,approved.constellations[code],code+' approved placement changed');assert.deepEqual(guides[code],approved.semanticGuides[code],code+' approved guides changed');}
});
test('catalog is exactly the original star names, positions and lines',()=>{const html=fs.readFileSync(path.join(root,'index.html'),'utf8'),source=JSON.parse(html.match(/const CONSTELLATIONS=(\[.*?\]);/s)[1]);for(const c of catalog){const original=source.find(i=>i.jp===c.jp);assert(original,c.jp);assert.deepEqual(c.stars,original.stars);assert.deepEqual(c.lines,original.lines);}});
test('five semantic fits improve rather than just matching centers',()=>{for(const code of pilot){const i=index.items.find(i=>i.code===code),c=catalog.find(i=>i.code===code),f=P.frame(i.anchors),g=guides[code],avg=a=>{const rows=P.errors(f,a,g,c.stars);return rows.reduce((s,r)=>s+r.errorDeg*r.weight,0)/rows.reduce((s,r)=>s+r.weight,0);};assert(avg(i.adjustment)<avg(P.DEFAULT)*.85,code);assert(avg(i.adjustment)<3,code);assert.deepEqual(i.adjustment,layout.items.find(i=>i.code===code).adjustment);}
 const gem=index.items.find(i=>i.code==='Gem'),c=catalog.find(i=>i.code==='Gem');for(const r of P.errors(P.frame(gem.anchors),gem.adjustment,guides.Gem.slice(0,2),c.stars))assert(r.errorDeg<.5,r.star);
});
test('numeric transforms keep pivot, support mirror and reject invalid values',()=>{const f=P.frame(index.items[0].anchors),base=P.map(f),m=P.map(f,{scale:2,rotationDeg:90,flipX:true,offsetX:3,offsetY:-4});assert(Math.abs(m.position[0]-base.position[0]-Math.tan(3*Math.PI/180))<1e-12);assert(Math.abs(m.position[1]-base.position[1]-Math.tan(-4*Math.PI/180))<1e-12);assert(Math.abs(m.u[0]-2*base.u[1])<1e-12);assert(Math.abs(m.u[1]+2*base.u[0])<1e-12);assert(Math.abs(Math.hypot(...m.v)/Math.hypot(...base.v)-2)<1e-12);assert.equal(P.validate({rotationDeg:360}).rotationDeg,0);for(const a of[{scale:NaN},{scale:0},{offsetX:81},{flipX:'false'},{offsetY:'1'},null,[]])assert.throws(()=>P.validate(a));});
test('symmetric guides do not fail when one handedness yields zero scale',()=>{const f=P.frame(index.items[0].anchors),uvs=[[.2,.2],[.8,.2],[.8,.8],[.2,.8]],stars=uvs.map((uv,n)=>({n:String(n),p:P.direction(f,...uv)})),g=uvs.map((uv,n)=>({star:String(n),uv,weight:1}));const result=P.fitGuides(f,g,stars);assert(result.errors.every(r=>r.errorDeg<1e-5));});
test('apply/export rejects stale or invalid data before mutation and keeps other entries',()=>{const exported=read('assets/constellations/calibration.json'),original=JSON.stringify(index),result=apply(exported,index,layout);assert.deepEqual(result.index,index);assert.equal(JSON.stringify(index),original);for(const value of[{...exported,baseVersion:'stale'},{...exported,constellations:{Unknown:P.DEFAULT}},{...exported,constellations:{Ori:{scale:0}}}])assert.throws(()=>apply(value,index,layout));assert.equal(JSON.stringify(index),original);});

test('all calibrated bodies have meaningful guides and consistent persisted transforms',()=>{for(const i of index.items){assert.deepEqual(P.validate(i.adjustment),i.adjustment);assert.deepEqual(i.adjustment,layout.items.find(x=>x.code===i.code).adjustment);const c=catalog.find(c=>c.code===i.code),g=guides[i.code];assert(g&&g.length,i.code);for(const x of g){assert(c.stars.some(s=>s.n===x.star));assert(x.uv.length===2&&x.uv.every(v=>v>=0&&v<=1));assert(x.role.length>0);}const rows=P.errors(P.frame(i.anchors),i.adjustment,g,c.stars);assert(rows.every(r=>Number.isFinite(r.errorDeg)));}});
test('two-star fitting prefers the existing handedness when both candidates fit equally',()=>{const i=index.items.find(i=>i.code==='CMi'),c=catalog.find(i=>i.code==='CMi');assert.equal(P.fitGuides(P.frame(i.anchors),guides.CMi,c.stars).adjustment.flipX,false);});
