const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium,devices}=require('playwright');
const base=process.env.SPACE_APP_TEST_URL||'http://127.0.0.1:8770/',url=base+'tools/constellation-calibrator.html',out=process.env.CALIBRATION_SCREENSHOTS||'/tmp/calibration',pilots=['Ori','Leo','And','Gem','Peg'];
const value=async p=>JSON.parse(await p.locator('#jsonOutput').inputValue()),current=async p=>Object.values((await value(p)).constellations)[0];
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});try{
 for(const profile of ['PC','iPhone']){
  const ctx=await b.newContext(profile==='PC'?{viewport:{width:1320,height:1000}}:{...devices['iPhone 13'],viewport:{width:390,height:844},deviceScaleFactor:1}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(url);await p.waitForFunction(()=>window.calibratorReady);assert.equal(await p.locator('#constellationSelect option').count(),34);assert.equal(Object.keys((await value(p)).constellations).length,34);
  for(const code of pilots){await p.selectOption('#constellationSelect',code);await p.waitForFunction(()=>document.getElementById('loading').hidden);await p.screenshot({path:path.join(out,profile+'-'+code+'.png'),fullPage:profile==='iPhone'});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert(await p.locator('#guideTable tr').count()>=4);}
  await p.selectOption('#constellationSelect','Ori');await p.waitForFunction(()=>document.getElementById('loading').hidden);await p.selectOption('#exportScope','current');const original=await current(p),box=await p.locator('#stage').boundingBox();
  if(profile==='PC'){await p.mouse.move(box.x+box.width*.5,box.y+box.height*.5);await p.mouse.down();await p.mouse.move(box.x+box.width*.5+25,box.y+box.height*.5-15,{steps:4});await p.mouse.up();}
  else{await p.locator('#stage').scrollIntoViewIfNeeded();const r=await p.locator('#stage').boundingBox(),cdp=await ctx.newCDPSession(p),touch=(type,points)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points.map(([x,y],id)=>({x,y,id}))});await touch('touchStart',[[r.x+100,r.y+120]]);await touch('touchMove',[[r.x+135,r.y+100]]);await touch('touchEnd',[]);const moved=await current(p);assert.notEqual(moved.offsetX,original.offsetX);await touch('touchStart',[[r.x+100,r.y+160],[r.x+200,r.y+160]]);await touch('touchMove',[[r.x+80,r.y+140],[r.x+220,r.y+180]]);await touch('touchEnd',[]);const pinched=await current(p);assert(pinched.scale>moved.scale);assert.notEqual(pinched.rotationDeg,moved.rotationDeg);}
  assert.notEqual((await current(p)).offsetX,original.offsetX);await p.locator('#rotationDeg').fill('45');assert.equal((await current(p)).rotationDeg,45);await p.locator('#scale').fill('1.25');assert.equal((await current(p)).scale,1.25);await p.locator('#flipX').setChecked(!original.flipX);assert.equal((await current(p)).flipX,!original.flipX);await p.locator('#opacity').evaluate(e=>{e.value='80';e.dispatchEvent(new Event('input'))});assert.equal(await p.locator('#opacityValue').textContent(),'80%');const edited=await current(p);await p.locator('#fitView').click();assert.deepEqual(await current(p),edited);await p.reload();await p.waitForFunction(()=>window.calibratorReady);await p.selectOption('#exportScope','current');assert.deepEqual(await current(p),edited);
  await p.locator('#reset').click();assert.deepEqual(await current(p),original);await p.locator('#baseline').click();assert.deepEqual(await current(p),{scale:1,rotationDeg:0,offsetX:0,offsetY:0,flipX:false});await p.locator('#autoFit').click();assert.deepEqual(await current(p),original);
  const snapshot=await value(p);await p.locator('#import').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...snapshot,constellations:{Ori:{scale:2},Unknown:{scale:1}}}))});await p.waitForFunction(()=>document.getElementById('status').textContent.includes('読み込み失敗'));assert.deepEqual(await current(p),original);
  const imported={...snapshot,constellations:{Ori:{...original,rotationDeg:12}}};await p.locator('#import').setInputFiles({name:'valid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(imported))});await p.waitForFunction(()=>document.getElementById('status').textContent.includes('読み込みました'));assert.equal((await current(p)).rotationDeg,12);await p.locator('#reset').click();
  const downloadPromise=p.waitForEvent('download');await p.locator('#save').click();const download=await downloadPromise;assert.equal(download.suggestedFilename(),'constellation-calibration.json');assert.deepEqual(JSON.parse(fs.readFileSync(await download.path())),await value(p));
  await ctx.grantPermissions(['clipboard-read','clipboard-write']);await p.locator('#copy').click();assert.deepEqual(JSON.parse(await p.evaluate(()=>navigator.clipboard.readText())),await value(p));
  await p.selectOption('#exportScope','all');assert.equal(Object.keys((await value(p)).constellations).length,34);await p.selectOption('#constellationSelect','Car');assert.equal(await p.locator('#autoFit').isDisabled(),true);await p.selectOption('#constellationSelect','Ori');await p.selectOption('#constellationSelect','Gem');await p.selectOption('#constellationSelect','Peg');await p.waitForFunction(()=>document.getElementById('loading').hidden);assert((await p.locator('#selectedName').textContent()).includes('ペガスス'));
  if(profile==='iPhone'){await p.setViewportSize({width:844,height:390});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:path.join(out,'iPhone-landscape.png'),fullPage:true});}
  assert.deepEqual(errors,[]);console.log(profile+': five previews, move/scale/rotation/flip/opacity, persistence, JSON copy/save/import passed');await ctx.close();
 }
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
