const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium,devices}=require('playwright');
const url=process.env.SPACE_APP_TEST_URL||'http://127.0.0.1:8770/';
const hooks=`window.__artTestStart=()=>{resetView();setScale0();showPose([0,0,0],[0,0,1],78);showMW=false;setSpeed(0);};
window.__artState=()=>({enabled:showConstArt,opacity:artOpacity,quality:constellationArtQuality(),items:constellationArt.map(a=>({code:a.code,loaded:!!a.texture,quality:a.quality})),error:gl.getError()});
window.__artFocus=code=>{resetView();setScale0();const a=constellationArt.find(a=>a.code===code),dir=constellationArtDirection(a.frame,.5,.5,a.adjustment);showPose([0,0,0],v3scale(dir,-1),78);setSpeed(0);};`;
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8').replace('  requestAnimationFrame(frame);\n})();',hooks+'\n  requestAnimationFrame(frame);\n})();');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--enable-unsafe-swiftshader','--use-angle=swiftshader']});const results=[];
try{for(const profile of ['PC','iPhone']){const page=await browser.newPage(profile==='PC'?{viewport:{width:1000,height:760}}:{...devices['iPhone 13'],viewport:{width:390,height:844},deviceScaleFactor:1});const errors=[],images=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.url().includes('.webp'))images.push(r.url())});await page.route(url,r=>r.fulfill({contentType:'text/html',body:html}));await page.addInitScript(()=>{localStorage.setItem('ssm_lite','0');window.__frames=0;const raf=requestAnimationFrame;window.requestAnimationFrame=cb=>raf.call(window,t=>{__frames++;cb(t)})});console.log('Starting '+profile);page.setDefaultTimeout(180000);await page.goto(url);await page.locator('#welcomeExplore').click();await page.evaluate(()=>__artTestStart());assert.equal(images.length,0,'Artwork loads only on demand');if(await page.locator('#panelToggle').getAttribute('aria-expanded')==='false')await page.locator('#panelToggle').click();await page.locator('#bConstArt').click();await page.waitForFunction(()=>document.querySelector('#bConstArt').dataset.load==='ready',{},{timeout:180000});console.log(profile+' textures ready');let state=await page.evaluate(()=>__artState());assert.equal(state.items.length,34);assert(state.items.every(a=>a.loaded&&a.quality===(profile==='PC'?'full':'mobile')));assert.equal(state.error,0);assert.equal(images.length,34);await page.locator('#constArtOpacity').evaluate(el=>{el.value='80';el.dispatchEvent(new Event('input'))});assert.equal((await page.evaluate(()=>__artState())).opacity,.8);await page.locator('#bConst').click();await page.locator('#panelToggle').click();
for(const code of ['Ori','Leo','And','Gem','Peg']){await page.evaluate(code=>__artFocus(code),code);const n=await page.evaluate(()=>__frames);await page.waitForFunction(n=>__frames>=n+2,n);assert.equal((await page.evaluate(()=>__artState())).error,0);await page.screenshot({path:'/tmp/constellation-'+profile+'-'+code+'.png'});}await page.locator('#panelToggle').click();await page.locator('#bLite').click();if(profile==='PC'){await page.waitForFunction(()=>__artState().items.every(a=>a.quality==='mobile'));assert.equal(images.length,68);}else{assert.equal(images.length,34);await page.setViewportSize({width:844,height:390});await page.waitForTimeout(500);assert.equal((await page.evaluate(()=>__artState())).quality,'mobile');}await page.locator('#bConstArt').click();assert.equal((await page.evaluate(()=>__artState())).enabled,false);await page.locator('#bConstArt').click();await page.waitForTimeout(300);assert.equal(images.length,profile==='PC'?68:34,'Toggle reuses textures');assert.equal(errors.length,0);results.push({profile,images:images.length,state:await page.evaluate(()=>__artState()),errors});await page.close();}
// A single missing texture remains retryable without rebuilding the other 33.
const p=await browser.newPage({viewport:{width:390,height:844}});p.setDefaultTimeout(180000);await p.route(url,r=>r.fulfill({contentType:'text/html',body:html}));let fail=true,requests=0;await p.route('**/mobile/andromeda.webp*',r=>{requests++;return fail?r.fulfill({status:404,body:''}):r.continue()});await p.goto(url);await p.locator('#welcomeExplore').click();await p.evaluate(()=>__artTestStart());if(await p.locator('#panelToggle').getAttribute('aria-expanded')==='false')await p.locator('#panelToggle').click();await p.locator('#bConstArt').click();await p.waitForFunction(()=>document.querySelector('#bConstArt').dataset.load==='partial');assert.equal((await p.evaluate(()=>__artState())).items.filter(a=>a.loaded).length,33);fail=false;await p.locator('#bConstArt').click();await p.locator('#bConstArt').click();await p.waitForFunction(()=>document.querySelector('#bConstArt').dataset.load==='ready');assert.equal(requests,2);await p.close();
fs.writeFileSync('/tmp/constellation-art-results.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results.map(r=>({profile:r.profile,requests:r.images,quality:r.state.quality,loaded:r.state.items.length,errors:r.errors}))))}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
