const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium,devices}=require('playwright');
const raw=require('./fixtures/iss-omm.json'),epoch=Date.parse(raw.fetchedAt),url=process.env.SPACE_APP_TEST_URL||'http://127.0.0.1:8770/';
const observation=`window.__earthState=()=>({width:earthTextureManager.width,target:earthTextureManager.target,failed:earthTextureManager.failed,busy:earthTextureManager.busy,base:earthColor===earthBaseTexture,iss:!!issState,ground:!!horizonCut,issSky,earthSynced,error:gl.getError(),eye:curEye,pos:issPos});window.__resumeFrames=()=>{window.__testFreeze=false;requestAnimationFrame(frame);};`;
const source=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8').replace('  function frame(now,stereoPass=0){','  function frame(now,stereoPass=0){if(window.__testFreeze)return;').replace('  requestAnimationFrame(frame);\n})();',observation+'\n  requestAnimationFrame(frame);\n})();');
(async()=>{const b=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--enable-unsafe-swiftshader','--use-angle=swiftshader']});const results=[];
try{for(const profile of ['PC','iPhone']){const p=await b.newPage(profile==='PC'?{viewport:{width:1000,height:760}}:{...devices['iPhone 13'],viewport:{width:390,height:844}});p.setDefaultTimeout(60000);const errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.addInitScript(({raw,epoch})=>{Date.now=()=>epoch+1200000;Object.defineProperty(navigator,'deviceMemory',{get:()=>8});Object.defineProperty(navigator,'hardwareConcurrency',{get:()=>8});localStorage.setItem('ssm_lite','0');localStorage.setItem('space-app.iss.omm.v1',JSON.stringify(raw));},{raw,epoch});
 await p.route(url,r=>r.fulfill({contentType:'text/html',body:source}));await p.route('https://raw.githubusercontent.com/enou123/space-app/iss-data/latest.json',r=>r.fulfill({json:raw}));await p.route('https://celestrak.org/**',r=>r.abort());
 await p.goto(url);await p.locator('#welcomeExplore').click();if(await p.locator('#panelToggle').getAttribute('aria-expanded')!=='true')await p.locator('#panelToggle').click();
 const state=()=>p.evaluate(()=>__earthState()),shot=async name=>{await p.evaluate(()=>window.__testFreeze=true);await p.waitForTimeout(150);await p.screenshot({path:'/tmp/earth-iss-'+profile+'-'+name+'.png'});await p.evaluate(()=>__resumeFrames());};
 await p.waitForFunction(()=>window.__earthState?.().width===2048);assert((await state()).base);await p.selectOption('#moonTravelSelect','iss');await p.waitForFunction(()=>__earthState().iss&&__earthState().width===4096);await p.locator('#issSky').click();await p.locator('#panelToggle').click();await shot('4096');console.log(profile,'4096 OK');
 if(profile==='PC'){await p.locator('#panelToggle').click();await p.selectOption('#earthQuality','8192');await p.waitForFunction(()=>__earthState().width===8192);await p.locator('#panelToggle').click();await shot('8192');console.log(profile,'8192 OK');}
 else{await p.locator('#panelToggle').click();await p.selectOption('#earthQuality','8192');await p.waitForFunction(()=>__earthState().target===4096);assert((await p.locator('#earthQualityNote').textContent()).includes('制限'));await p.setViewportSize({width:844,height:390});await p.locator('#panelToggle').click();await shot('landscape');}
 let s=await state();assert.equal(s.ground,false);assert(s.earthSynced);assert.equal(s.error,0);
 await p.locator('#panelToggle').click();await p.selectOption('#earthQuality','2048');await p.waitForFunction(()=>__earthState().base&&__earthState().width===2048);
 await p.route('**/assets/textures/earth-blue-marble-4096.jpg',r=>r.abort());await p.selectOption('#earthQuality','4096');await p.waitForFunction(()=>__earthState().failed);s=await state();assert.equal(s.width,2048);assert(s.base);assert((await p.locator('#earthQualityNote').textContent()).includes('標準画像'));assert.equal(s.error,0);
 await p.unroute('**/assets/textures/earth-blue-marble-4096.jpg');await p.selectOption('#earthQuality','auto');await p.waitForFunction(()=>__earthState().width===4096);await p.locator('#bLite').click();await p.waitForFunction(()=>__earthState().width===2048);assert((await state()).base);
 assert.equal(errors.length,0,JSON.stringify(errors));results.push({profile,optional:profile==='PC'?[4096,8192]:[4096],gpuError:s.error,mobileCap:true,failureFallback:true,liteFallback:true,errors});await p.close();}
}finally{await b.close();}fs.writeFileSync('/tmp/earth-texture-browser-results.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results));})().catch(e=>{console.error(e);process.exit(1)});
