const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium,devices}=require('playwright');
(async()=>{const b=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--enable-unsafe-swiftshader','--use-angle=swiftshader']});const results=[];
try{for(const profile of ['PC','iPhone','landscape']){
 const p=await b.newPage(profile==='PC'?{viewport:{width:1000,height:760}}:{...devices['iPhone 13'],viewport:profile==='landscape'?{width:844,height:390}:{width:390,height:844},deviceScaleFactor:1});const errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&!m.text().includes('404'))errors.push(m.text())});
 const url=process.env.SPACE_APP_TEST_URL||'http://127.0.0.1:8770/';const source=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8').replace('  requestAnimationFrame(frame);\n})();',fs.readFileSync(path.join(__dirname,'browser-observability.js'),'utf8')+'\n  requestAnimationFrame(frame);\n})();');await p.route(url,r=>r.fulfill({contentType:'text/html',body:source}));await p.addInitScript(()=>{localStorage.setItem('ssm_lite','1');window.__frames=0;const raf=requestAnimationFrame;window.requestAnimationFrame=cb=>raf.call(window,t=>{__frames++;cb(t)})});await p.goto(url);await p.locator('#welcomeExplore').click();await p.selectOption('#celestialShowSelect','halley');
 const frame=async()=>{const n=await p.evaluate(()=>__frames);await p.waitForFunction(n=>__frames>=n+2,n)};await frame();await p.waitForFunction(()=>getComputedStyle(document.querySelector('#welcome')).opacity==='0');const sweep=await p.evaluate(()=>__halleyCameraSweep());assert(sweep.minCross>.15&&sweep.maxRoll<.15,'Camera turns without a sudden roll: '+JSON.stringify(sweep));const samples=[];
 for(const t of [0,12,20,24,28,30,31,32,33,34,35,36,38,39,40,44,47,50,52,55,56,57,58,59,60,61,63,64,70,76,84]){
  await p.evaluate(t=>__showsSeek(t),t);await frame();const s=await p.evaluate(()=>__tourState());assert(s.finite&&!s.error&&!errors.length);const rect=await p.locator('#guide').boundingBox(),size=p.viewportSize();
  const visible=(point,label)=>{assert(point&&point[0]>10&&point[0]<size.width-10&&point[1]>60&&point[1]<size.height-10,profile+' '+label+' at '+t+': '+JSON.stringify(point));assert(!(point[0]>rect.x&&point[0]<rect.x+rect.width&&point[1]>rect.y&&point[1]<rect.y+rect.height),label+' hidden by the guide at '+t);};
  if(t>=28){visible(s.sun,'Sun');visible(s.points[0],'Comet');if([28,40,44,47,50,52,70,76,84].includes(t))s.points.forEach(pt=>visible(pt,'Tail'));}
  const distance=Math.hypot(...s.eye.map((v,k)=>v-s.halley.head[k]));samples.push({t,shot:s.shot,distance,screenAngle:s.sun&&s.points[0]?Math.atan2(s.points[0][1]-s.sun[1],s.points[0][0]-s.sun[0]):null});
  const ion=s.halley.dir,head=s.halley.head;assert(ion.reduce((v,x,k)=>v+x*head[k],0)>0,'Ion tail points away from Sun');
  if([28,34,47,59,84].includes(t))await p.screenshot({path:'/tmp/halley-camera-'+profile+'-'+t+'.png'});
 }
 const distance=t=>samples.find(s=>s.t===t).distance;assert(distance(34)<distance(28)/20&&distance(59)<distance(47)/20,'Two close camera passes');assert(samples.find(s=>s.t===34).shot==='flyby'&&samples.find(s=>s.t===59).shot==='flyby');
 const a=samples.find(s=>s.t===40).screenAngle,c=samples.find(s=>s.t===52).screenAngle;assert(Math.abs(Math.atan2(Math.sin(c-a),Math.cos(c-a)))>.8,'Comet visibly turns around the Sun in the wide view');
 await p.evaluate(()=>__showsSeek(47));await frame();await p.locator('#gShowPause').click();await frame();await p.locator('#gShowPause').click();const paused=await p.evaluate(()=>__tourState());await frame();assert.equal((await p.evaluate(()=>__tourState())).years,paused.years);assert.deepEqual((await p.evaluate(()=>__tourState())).cam,paused.cam);const originalSize=p.viewportSize();await p.setViewportSize(profile==='iPhone'?{width:844,height:390}:{width:390,height:844});await frame();const resized=await p.evaluate(()=>__tourState());assert.equal(resized.years,paused.years);const r=await p.locator('#guide').boundingBox();for(const point of [resized.sun,resized.points[0]]){assert(point&&point[0]>0&&point[0]<p.viewportSize().width&&point[1]>0&&point[1]<p.viewportSize().height);assert(!(point[0]>r.x&&point[0]<r.x+r.width&&point[1]>r.y&&point[1]<r.y+r.height),'Paused scene adapts to orientation');}await p.setViewportSize(originalSize);await frame();await p.locator('#gEnd').click();assert.equal((await p.evaluate(()=>__showsState())).show,null);
 assert.equal(errors.length,0);results.push({profile,samples,errors});console.log(JSON.stringify(results.at(-1)));await p.close();
}}finally{await b.close();}fs.writeFileSync('/tmp/halley-camera-results.json',JSON.stringify(results,null,2));})().catch(e=>{console.error(e);process.exit(1)});
