const fs=require('fs'),assert=require('assert/strict'),{chromium,devices}=require('playwright'),raw=require('./fixtures/iss-omm.json');
const url=process.env.SPACE_APP_TEST_URL||'http://127.0.0.1:8770/',epoch=Date.parse(raw.fetchedAt);
const observation=`window.__issGeometry=()=>({followISS,issSky,d:cam.td,unit:ISS_KM_UNIT,angle:issState?Math.asin(6371/Math.hypot(...issState.position))*180/Math.PI:null,ground:!!horizonCut,error:gl.getError()});window.__issPose=wide=>{window.__poseToken=(window.__poseToken||0)+1;issCentered=false;if(wide){issSky=false;cam.d=cam.td=ISS_KM_UNIT*15000;const dir=v3norm(v3sub(issPos,bodyAt(BODIES[2],years,false)));cam.th=cam.tth=Math.atan2(dir[0],dir[2]);cam.ph=cam.tph=Math.acos(dir[1]);}else{issSky=true;const dir=v3norm(v3sub(bodyAt(BODIES[2],years,false),issPos)),ph=Math.acos(dir[1]);cam.th=cam.tth=Math.atan2(dir[0],dir[2]);cam.ph=cam.tph=ph+(ph<Math.PI/2?1.15:-1.15);}};window.__resumeFrames=()=>{window.__testFreeze=false;requestAnimationFrame(frame);};`;
const source=fs.readFileSync('index.html','utf8').replace('  function frame(now,stereoPass=0){','  function frame(now,stereoPass=0){if(window.__testFreeze)return;').replace('    requestAnimationFrame(frame);\n  }','    window.__renderedPose=window.__poseToken;requestAnimationFrame(frame);\n  }').replace('  requestAnimationFrame(frame);\n})();',observation+'\n  requestAnimationFrame(frame);\n})();');
(async()=>{const b=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--enable-unsafe-swiftshader','--use-angle=swiftshader']});const results=[];try{
for(const profile of (process.env.SPACE_APP_TEST_PROFILE?[process.env.SPACE_APP_TEST_PROFILE]:['PC','iPhone'])){const p=await b.newPage(profile==='PC'?{viewport:{width:1000,height:760}}:{...devices['iPhone 13'],viewport:{width:390,height:844}});p.setDefaultTimeout(60000);const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(({raw,epoch})=>{Date.now=()=>epoch+300000;localStorage.setItem('ssm_lite','1');localStorage.setItem('space-app.iss.omm.v1',JSON.stringify(raw));},{raw,epoch});await p.route(url,r=>r.fulfill({body:source,contentType:'text/html'}));await p.route('https://raw.githubusercontent.com/enou123/space-app/iss-data/latest.json',r=>r.fulfill({json:raw}));await p.route('https://celestrak.org/**',r=>r.abort());await p.goto(url);await p.locator('#welcomeExplore').click();if(await p.locator('#panelToggle').getAttribute('aria-expanded')!=='true')await p.locator('#panelToggle').click();await p.selectOption('#moonTravelSelect','iss');await p.waitForFunction(()=>__issGeometry().angle);await p.locator('#panelToggle').click();const before=await p.evaluate(()=>__issGeometry());
 if(profile==='iPhone'){await p.evaluate(()=>{const c=document.querySelector('canvas'),send=(type,id,x)=>c.dispatchEvent(new PointerEvent(type,{pointerType:'touch',pointerId:id,clientX:x,clientY:300,button:0,buttons:type==='pointerup'?0:1,bubbles:true}));send('pointerdown',11,150);send('pointerdown',12,230);send('pointermove',11,120);send('pointermove',12,260);});await p.waitForFunction(d=>__issGeometry().d<d,before.d);await p.evaluate(()=>{for(const id of [11,12])window.dispatchEvent(new PointerEvent('pointerup',{pointerType:'touch',pointerId:id}));});assert((await p.evaluate(()=>__issGeometry())).followISS);}
 else{await p.mouse.move(600,250);await p.mouse.wheel(0,-100);await p.waitForFunction(d=>__issGeometry().d<d,before.d);}
 const shot=async name=>{await p.waitForFunction(()=>window.__renderedPose===window.__poseToken);await p.evaluate(()=>window.__testFreeze=true);await p.waitForTimeout(150);await p.screenshot({path:'/tmp/iss-geometry-'+profile+'-'+name+'.png'});await p.evaluate(()=>__resumeFrames());};
 await p.evaluate(()=>__issPose(true));await p.waitForFunction(()=>__issGeometry().d===__issGeometry().unit*15000);await shot('earth-and-iss');await p.locator('#panelToggle').click();await p.locator('#issSky').click();await p.locator('#panelToggle').click();await p.evaluate(()=>__issPose(false));await p.waitForTimeout(300);await shot('horizon');const s=await p.evaluate(()=>__issGeometry());assert.equal(s.ground,false);assert(s.angle>69&&s.angle<71);assert.equal(s.error,0);assert.equal(errors.length,0,JSON.stringify(errors));results.push({profile,earthAngularRadius:s.angle,zoom:true,pinch:profile==='iPhone',errors});await p.close();}
}finally{await b.close();}fs.writeFileSync('/tmp/iss-geometry-results.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results));})().catch(e=>{console.error(e);process.exit(1)});
