const {chromium,devices}=require('playwright'),fs=require('fs'),assert=require('assert/strict'),crypto=require('crypto'),path=require('path');
// Public HTML/assets/snapshot stay real; block upstream to avoid test download bursts.
const url=process.env.SPACE_APP_TEST_URL||'https://enou123.github.io/space-app/';
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE||'/usr/bin/chromium',...(process.env.HTTPS_PROXY?{proxy:{server:process.env.HTTPS_PROXY,bypass:'127.0.0.1,localhost'}}:{}),args:['--no-sandbox','--enable-unsafe-swiftshader','--use-angle=swiftshader']});const results=[];
for(const profile of ['PC','iPhone-portrait','iPhone-landscape']){
 console.log('start',profile);const context=await browser.newContext(profile==='PC'?{viewport:{width:1000,height:760}}:{...devices['iPhone 13'],deviceScaleFactor:1,viewport:profile.endsWith('portrait')?{width:390,height:844}:{width:844,height:390}});await context.route('https://celestrak.org/**',r=>r.abort('blockedbyclient'));const p=await context.newPage(),errors=[],network=[],failed=[];p.setDefaultTimeout(90000);const click=async selector=>profile==='PC'?p.locator(selector).click():p.locator(selector).tap();
 const jsErrors=[];p.on('pageerror',e=>jsErrors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});p.on('requestfailed',r=>(failed.push({url:r.url(),error:r.failure()?.errorText}),console.log(profile,'FAILED',r.url(),r.failure()?.errorText)));p.on('response',r=>{if(/celestrak|iss-data|earth-blue-marble/.test(r.url())||r.status()>=400)(network.push({url:r.url(),status:r.status()}),console.log(profile,'HTTP',r.status(),r.url()))});
 await p.addInitScript(()=>{localStorage.setItem('ssm_lite','1');window.__gpu={draws:0};const get=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(...a){const gl=get.apply(this,a);if(gl&&a[0].startsWith('webgl')){window.__releaseGL=gl;const draw=gl.drawElements;gl.drawElements=function(...args){__gpu.draws++;return draw.apply(this,args)}}return gl}});
 const response=await p.goto(url,{waitUntil:'load'});assert.equal(response.status(),200);const html=await response.text();assert.equal(crypto.createHash('sha256').update(html).digest('hex'),crypto.createHash('sha256').update(fs.readFileSync(path.join(__dirname,'../index.html'))).digest('hex'),'deployed HTML matches release');
 await click('#welcomeExplore');if(await p.locator('#panelToggle').getAttribute('aria-expanded')!=='true')await click('#panelToggle');await p.selectOption('#moonTravelSelect','iss');
 await p.waitForFunction(()=>document.querySelector('canvas').dataset.iss==='visible');await p.waitForFunction(()=>!document.querySelector('#issStatus').textContent.includes('更新中'));const acquisitionStatus=await p.locator('#issStatus').textContent(),dataSource=acquisitionStatus.includes('CelesTrak')?'live':'snapshot';assert(acquisitionStatus.includes('公開サイトのキャッシュ'));console.log(profile,'acquisition',dataSource,acquisitionStatus);
 assert(await p.locator('[data-sc="2"]').evaluate(e=>e.classList.contains('on')));assert(await p.locator('[data-sp="0.0000011408"]').evaluate(e=>e.classList.contains('on')));
 const status1=await p.locator('#issStatus').textContent(),date1=await p.locator('#simDate').textContent();await p.waitForFunction(s=>document.querySelector('#issStatus').textContent!==s,status1);const status2=await p.locator('#issStatus').textContent();assert(/高度 \d+/.test(status2));assert(/速度 7\.\d+ km\/s/.test(status2));
 await click('#bLite');const capabilities=await p.evaluate(()=>({memory:navigator.deviceMemory,cores:navigator.hardwareConcurrency,maxTextureSize:__releaseGL.getParameter(__releaseGL.MAX_TEXTURE_SIZE)}));await p.selectOption('#earthQuality','8192');const nativeResolution=await p.evaluate(()=>EarthTexture.resolution('8192',{maxTextureSize:__releaseGL.getParameter(__releaseGL.MAX_TEXTURE_SIZE),mobile:/iPhone|iPad|Android/.test(navigator.userAgent),memory:navigator.deviceMemory||4,cores:navigator.hardwareConcurrency||4},true));await p.waitForFunction(w=>document.querySelector('canvas').dataset.earthResolution===String(w),nativeResolution);console.log(profile,'native resolution OK',capabilities);let optional8192=false;if(profile==='PC'&&capabilities.maxTextureSize>=8192&&nativeResolution<8192){await p.evaluate(()=>{Object.defineProperty(navigator,'deviceMemory',{get:()=>8,configurable:true});Object.defineProperty(navigator,'hardwareConcurrency',{get:()=>8,configurable:true});});await p.selectOption('#earthQuality','2048');await p.selectOption('#earthQuality','8192');await p.waitForFunction(()=>document.querySelector('canvas').dataset.earthResolution==='8192');optional8192=true;console.log(profile,'8192 supported-capability simulation OK');}
 await click('#issSky');assert(await p.locator('#issSky').evaluate(e=>e.classList.contains('on')));await click('#panelToggle');await p.mouse.move(p.viewportSize().width*.75,p.viewportSize().height*.3);await p.mouse.down();await p.mouse.move(p.viewportSize().width*.9,p.viewportSize().height*.55,{steps:5});await p.mouse.up();await p.mouse.wheel(0,-90);if(profile!=='PC'){const cdp=await context.newCDPSession(p),w=p.viewportSize().width,h=p.viewportSize().height;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:w*.6,y:h*.3}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:w*.75,y:h*.4}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:w*.6,y:h*.3,id:1},{x:w*.75,y:h*.3,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:w*.55,y:h*.3,id:1},{x:w*.8,y:h*.3,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();}
 await click('#panelToggle');await click('#issEarth');await click('#panelToggle');await p.waitForTimeout(500);await p.screenshot({path:'/tmp/published-'+profile+'.png'});
 const gl=await p.evaluate(()=>({error:__releaseGL.getError(),lost:__releaseGL.isContextLost(),draws:__gpu.draws}));assert.equal(gl.error,0);assert.equal(gl.lost,false);assert(gl.draws>10);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await click('#panelToggle');await click('#issSync');await click('#issLeave');await p.selectOption('#moonTravelSelect','5:0');await click('#bSurface');await click('#bOrbitView');
 const cachedElements=await p.evaluate(()=>{const x=JSON.parse(localStorage.getItem('space-app.iss.omm.v1'));return {norad:x.elements.NORAD_CAT_ID,epoch:x.elements.EPOCH,fetchedAt:x.fetchedAt};});assert.equal(Number(cachedElements.norad),25544);
 assert.equal(jsErrors.length,0,JSON.stringify(jsErrors));results.push({profile,url,cachedElements,acquisitionStatus,upstreamIntentionallyBlocked:true,htmlMatchesRelease:true,source:dataSource,statusBefore:status1,statusAfter:status2,date1,realScale:true,realTimeButton:true,skyCamera:true,dragWheelAndRecenter:true,earthResolution:optional8192?8192:nativeResolution,nativeResolution,capabilities,optional8192WithSimulatedCapabilities:optional8192,gl,jsErrors,errors,failed,network});console.log('PASS',profile,JSON.stringify(results.at(-1)));await context.close();
}
 const nasaPage=await browser.newPage();const nr=await nasaPage.goto('https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/8000/8108/ipcc_bluemarble_west_front.jpg/jcr:content/renditions/cq5dam.web.1280.1280.jpeg');assert.equal(nr.status(),200);const nasa=await nasaPage.locator('img').evaluate(async img=>{await img.decode();return {url:img.src,width:img.naturalWidth,height:img.naturalHeight};});await nasaPage.screenshot({path:'/tmp/published-nasa.png'});results.push({nasa,status:nr.status()});await nasaPage.close();await browser.close();fs.writeFileSync('/tmp/iss-published-results.json',JSON.stringify(results,null,2));})().catch(e=>{console.error(e);process.exit(1)});
